name: Notify Parent Repo
on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ahallemberg/pages.askhb.no
          event-type: submodule-updated
          client-payload: |
            {
              "submodule": "${{ github.repository }}",
              "ref": "${{ github.sha }}"
            }